export const WORKS = [
    {
        id: 0,
        link: "https://lounge-zebra.web.app/",
        title: "lounge",
        desc: "Web-site with my own design",
        tech: "Rect/SCSS",
    },
    {
        id: 1,
        link: "https://t.me/YourFillBot",
        title: "Manage Bot",
        desc: "Telegram Bot for manage your spending money and the result of your feelings during the day",
        tech: "NodeJS",
    },
    {
        id: 2,
        link: "https://icecream-tata.firebaseapp.com/",
        title: "ice-cream",
        desc: "Web-site with design copied from wix.com",
        tech: "Rect/SCSS",
    },
    {
        id: 3,
        link: "https://sudoku-ts.web.app/",
        title: "sudoku",
        desc: "Sudoku web-game",
        tech: "React/TypeScript",
    },
    {
        id: 4,
        link: "https://otpusklogin.web.app/",
        title: "otpusk",
        desc: 'Small example of search vacation. You can login with Email: "admin@gmail.com" and password: "admin"',
        tech: "Rect/SCSS",
    },
    {
        id: 5,
        link: "https://tatarozhdez.github.io/Random_Joke/",
        title: "Random joke",
        desc: "Generator of random jokes from Chuck Noris",
        tech: "JS/Html/Css",
    },
    {
        id: 6,
        link: "https://pht-gallery.web.app/",
        title: "photo gallery",
        desc: "Simple web-application with photo gallery.",
        tech: "Rect/SCSS",
    },
    {
        id: 7,
        link: "https://combination-trainer.web.app/",
        title: "combination-trainer",
        desc: "The game developed for practice hand detection in poker",
        tech: "React/SCSS",
    },
    {
        id: 8,
        link: "https://time-tracker-tata.web.app/",
        title: "time tracker",
        desc: "Simple timer",
        tech: "React",
    },
];
